/* tslint:disable */
// @ts-nocheck
const { writeFile } = require('fs');
const { argv } = require('yargs');

require('dotenv').config(); // read the env variables from .env file
const environment = argv.environment; // read the command line arguments passed with yargs

const isProduction = environment === 'prod'; // as `--environment=prod` option provided
const targetPath = isProduction
  ? './src/environments/environment.prod.ts'
  : './src/environments/environment.ts'; // choose targetPath based on environment
const environmentFileContent = `
  // This file was autogenerated by dynamically running setenv.ts and using dotenv for managing API key secrecy

  export const environment = {
    production: ${isProduction},
    FIREBASE_API_KEY: '${process.env.FIREBASE_API_KEY}'
  };
`; //content to be compiled dynamically and pasted into respective environment files

// write the content to the respective file
writeFile(targetPath, environmentFileContent, function (err) {
  if (err) {
    console.log(err);
  }
  console.log(`wrote variables to ${targetPath}`);
});
/* tslint:enable */
